---
title: "Untitled"
output: github_document
always_allow_html: true

#Bhan, Lam (2022) [Nanyang Technological University]
#ORCID: 0000-0001-5193-6560
#GitHub: https://github.com/bhanlam/
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pander)
library(dataverse)
library(tibble)
library(readxl)
library(plyr)
library(dplyr)

```

This repository contains the code accompanying the publication "Do uHear? Validation of uHear App for Preliminary Screening of Hearing Ability in Soundscape Studies". This paper is hosted on [arXiv]() and the raw dataset is hosted at [10.21979/N9/0NE37R](https://doi.org/10.21979/N9/0NE37R).

## Environment

The code has been tested on the following platform.

```{r session, message=FALSE, echo=FALSE}
pander(sessionInfo())
```

## Data preparation

Load data from excel

```{r dataloader, message=FALSE}
#load data into dataframe
dataset <- tibble::as_tibble(read_excel("Hearing test result.xlsx",skip = 0))


#prepare data in dataframe for analysis
cols2fac <- c("Participant ID", "Gender", "Type", "Ear")

cleandata <- dataset %>% 
        filter(complete.cases(.)) %>% #remove incomplete cases
        mutate_at(cols2fac,factor) #convert variable to factor

```

## Exploratory analysis

```{r demographics}

```



